### ISSUE TITLE
Code for the human evaluation of the WMT 2019 shared task on news translation.

### ISSUE THREAD

**Issue by pmarcis** [cfedermann/Appraise#62]
Hi Christian,

I see that the code has not changed since 2018.
I wanted to ask whether the code of this year’s WMT evaluation platform (for news evaluation) will be available?

Best regards,
Mārcis.

**Comment by pmarcis** [comment]
Hi Christian,

Do you plan to release the code for WMT 2019 or WMT 2020?

Best regards,
Mārcis.

**Comment by tomsbergmanis** [comment]
![image](https://user-images.githubusercontent.com/3306933/112651731-59822d80-8e55-11eb-83a0-8c8e5f07525e.png)

**Comment by snukky** [comment]
Hi @pmarcis, @tomsbergmanis, Appraise with evaluation tasks used at WMT19 and WMT20 has been recently released here: https://github.com/AppraiseDev/Appraise, which is the new official home for open-source Appraise.

**Comment by pmarcis** [comment]
Thanks @snukky !
